export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES';

export const INCREMENT = 'INCREMENT';

export const SET_FILTER_FIELDS = 'SET_FILTER_FIELDS';

export const ADD_COMMENT = 'ADD_COMMENT';